version: "3.5"

services:
  payment_agent:
    build: .
    image: payment_agent/anna
    command: flask run #./commands/${RUN_MODE}.sh
    volumes:
      - .:/usr/src/app
    ports:
      - 5000:${WSGI_PORT}
    env_file:
      - ./.env

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./main/static:/usr/src/app/main/static

