version: "3.5"

services:
  payment_agent:
    build: .
    image: payment_agent/anna
    command: python wsgi.py
    volumes:
      - .:/usr/src/app
    ports:
      - ${WSGI_PORT}:${WSGI_PORT}
    env_file:
      - ./.env

  nginx:
    image: nginx:1.18-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./main/static:/usr/src/app/payment_agent
    depends_on:
      - payment_agent


#  certbot:
#    image: certbot/certbot
#    restart: unless-stopped
#    volumes:
#      - ./data/certbot/conf:/etc/letsencrypt
#      - ./data/certbot/www:/var/www/certbot
#    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

