version: "3.5"

services:
  payment_agent:
    build: .
    image: payment_agent/anna
    command: gunicorn -w $NUM_WORKERS wsgi:app -b 0:$WSGI_PORT --log-level $LOG_LEVEL
    volumes:
      - .:/usr/src/app
    ports:
      - ${WSGI_PORT}:${WSGI_PORT}
    env_file:
      - ./.env

  nginx:
    image: nginx:1.18-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./main/static:/usr/src/app/payment_agent
    depends_on:
      - payment_agent

